/**
 * Shared markdown parser for UI generators
 * Returns a JavaScript function code string that can be embedded in generated code
 */

/**
 * Returns a lightweight markdown parser function as a string
 * This function converts markdown text to HTML for display in the panel
 * Supports: headings, bold, italic, strikethrough, code blocks, inline code,
 * blockquotes, horizontal rules, links, lists, and tables
 * @returns {string} - JavaScript function code string
 */
export function getMarkdownParserCode() {
  // Using regular string concatenation to avoid template literal escaping issues
  const code = [
    'function parseMarkdown(text) {',
    '  if (!text) return "";',
    '  let html = text;',
    '',
    '  // Escape HTML to prevent XSS',
    '  html = html.replace(/&/g, "&amp;")',
    '             .replace(/</g, "&lt;")',
    '             .replace(/>/g, "&gt;");',
    '',
    '  // Code blocks (must be processed before other elements)',
    '  html = html.replace(/```([\\s\\S]*?)```/g, function(match, code) {',
    '    return "<pre><code>" + code.trim() + "</code></pre>";',
    '  });',
    '',
    '  // Inline code',
    '  html = html.replace(/`([^`]+)`/g, "<code>$1</code>");',
    '',
    '  // Headings (process from h6 to h1 to avoid matching issues)',
    '  html = html.replace(/^###### (.+)$/gm, "<h6>$1</h6>");',
    '  html = html.replace(/^##### (.+)$/gm, "<h5>$1</h5>");',
    '  html = html.replace(/^#### (.+)$/gm, "<h4>$1</h4>");',
    '  html = html.replace(/^### (.+)$/gm, "<h3>$1</h3>");',
    '  html = html.replace(/^## (.+)$/gm, "<h2>$1</h2>");',
    '  html = html.replace(/^# (.+)$/gm, "<h1>$1</h1>");',
    '',
    '  // Bold (both ** and __)',
    '  html = html.replace(/\\*\\*(.+?)\\*\\*/g, "<strong>$1</strong>");',
    '  html = html.replace(/__(.+?)__/g, "<strong>$1</strong>");',
    '',
    '  // Italic (both * and _)',
    '  html = html.replace(/\\*([^*]+)\\*/g, "<em>$1</em>");',
    '  html = html.replace(/_([^_]+)_/g, "<em>$1</em>");',
    '',
    '  // Strikethrough',
    '  html = html.replace(/~~(.+?)~~/g, "<del>$1</del>");',
    '',
    '  // Blockquotes',
    '  html = html.replace(/^&gt; (.+)$/gm, "<blockquote>$1</blockquote>");',
    '',
    '  // Horizontal rule',
    '  html = html.replace(/^---$/gm, "<hr>");',
    '  html = html.replace(/^\\*\\*\\*$/gm, "<hr>");',
    '',
    '  // Links',
    '  html = html.replace(/\\[([^\\]]+)\\]\\(([^)]+)\\)/g, \'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>\');',
    '',
    '  // Unordered lists',
    '  html = html.replace(/^[*-] (.+)$/gm, "<li>$1</li>");',
    '  html = html.replace(/(<li>.*<\\/li>\\n?)+/g, "<ul>$&</ul>");',
    '',
    '  // Ordered lists',
    '  html = html.replace(/^\\d+\\. (.+)$/gm, "<li>$1</li>");',
    '',
    '  // Tables - parse markdown tables with header, separator, and body rows',
    '  html = (function(input) {',
    '    var lines = input.split("\\n");',
    '    var result = [];',
    '    var i = 0;',
    '    while (i < lines.length) {',
    '      var line = lines[i];',
    '      // Check if this line starts a table (starts and ends with |)',
    '      if (/^\\|.+\\|$/.test(line.trim())) {',
    '        var tableLines = [];',
    '        // Collect all consecutive table lines',
    '        while (i < lines.length && /^\\|.+\\|$/.test(lines[i].trim())) {',
    '          tableLines.push(lines[i].trim());',
    '          i++;',
    '        }',
    '        // Need at least 2 lines (header + separator) to be a valid table',
    '        if (tableLines.length >= 2) {',
    '          var separatorIndex = -1;',
    '          // Find the separator row (contains only |, -, :, and spaces)',
    '          for (var j = 0; j < tableLines.length; j++) {',
    '            if (/^\\|[\\s\\-:|]+\\|$/.test(tableLines[j])) {',
    '              separatorIndex = j;',
    '              break;',
    '            }',
    '          }',
    '          if (separatorIndex > 0) {',
    '            // Valid table found',
    '            var tableHtml = "<table>";',
    '            // Process header rows (before separator)',
    '            tableHtml += "<thead>";',
    '            for (var h = 0; h < separatorIndex; h++) {',
    '              var headerCells = tableLines[h].slice(1, -1).split("|").map(function(c) { return c.trim(); });',
    '              tableHtml += "<tr>" + headerCells.map(function(c) { return "<th>" + c + "</th>"; }).join("") + "</tr>";',
    '            }',
    '            tableHtml += "</thead>";',
    '            // Process body rows (after separator)',
    '            if (separatorIndex < tableLines.length - 1) {',
    '              tableHtml += "<tbody>";',
    '              for (var b = separatorIndex + 1; b < tableLines.length; b++) {',
    '                var bodyCells = tableLines[b].slice(1, -1).split("|").map(function(c) { return c.trim(); });',
    '                tableHtml += "<tr>" + bodyCells.map(function(c) { return "<td>" + c + "</td>"; }).join("") + "</tr>";',
    '              }',
    '              tableHtml += "</tbody>";',
    '            }',
    '            tableHtml += "</table>";',
    '            result.push(tableHtml);',
    '          } else {',
    '            // No separator found, not a valid table - output as-is',
    '            result.push.apply(result, tableLines);',
    '          }',
    '        } else {',
    '          // Single line that looks like table but is not - output as-is',
    '          result.push.apply(result, tableLines);',
    '        }',
    '      } else {',
    '        result.push(line);',
    '        i++;',
    '      }',
    '    }',
    '    return result.join("\\n");',
    '  })(html);',
    '',
    '  // Paragraphs - wrap text blocks that are not already wrapped in block elements',
    '  var lines = html.split("\\n");',
    '  var blockElements = ["<h1", "<h2", "<h3", "<h4", "<h5", "<h6", "<ul", "<ol", "<li", "<pre", "<blockquote", "<hr", "<table", "<thead", "<tbody", "<tr"];',
    '  html = lines.map(function(line) {',
    '    var trimmed = line.trim();',
    '    if (!trimmed) return "";',
    '    var isBlock = blockElements.some(function(tag) { return trimmed.startsWith(tag); });',
    '    if (isBlock) return line;',
    '    return "<p>" + line + "</p>";',
    '  }).filter(function(line) { return line; }).join("\\n");',
    '',
    '  // Clean up empty paragraphs and fix nested issues',
    '  html = html.replace(/<p><\\/p>/g, "");',
    '  html = html.replace(/<p>(<h[1-6]>)/g, "$1");',
    '  html = html.replace(/(<\\/h[1-6]>)<\\/p>/g, "$1");',
    '  html = html.replace(/<p>(<ul>)/g, "$1");',
    '  html = html.replace(/(<\\/ul>)<\\/p>/g, "$1");',
    '  html = html.replace(/<p>(<pre>)/g, "$1");',
    '  html = html.replace(/(<\\/pre>)<\\/p>/g, "$1");',
    '  html = html.replace(/<p>(<blockquote>)/g, "$1");',
    '  html = html.replace(/(<\\/blockquote>)<\\/p>/g, "$1");',
    '  html = html.replace(/<p>(<table>)/g, "$1");',
    '  html = html.replace(/(<\\/table>)<\\/p>/g, "$1");',
    '  html = html.replace(/<p>(<hr>)/g, "$1");',
    '  html = html.replace(/(<hr>)<\\/p>/g, "$1");',
    '',
    '  return html;',
    '}',
  ];
  return code.join('\n');
}
